In [139]:
import numpy as np

In [141]:
class CustomLinearRegression:
  def __init__(self, X_data, y_target, learning_rate = 0.01, num_epochs = 10000):
      self.num_samples = X_data.shape[0]
      self.X_data = np.c_[np.ones(self.num_samples), X_data]
      self.y_target = y_target
      self.learning_rate = learning_rate
      self.num_epochs = num_epochs

      self.theta = np.random.randn(self.X_data.shape[1], 1)
      self.losses = []

  def compute_loss(self, y_pred, y_target):
    loss = np.mean((y_pred - y_target) ** 2)
    return loss

  def predict(self, X_data):
    return X_data.dot(self.theta)

  def fit(self):
    for epoch in range(self.num_epochs):
      y_pred = self.predict(self.X_data)

      loss = self.compute_loss(y_pred, self.y_target)
      self.losses.append(loss)

      loss_grd = 2*(y_pred - self.y_target).dot(self.X_data) / self.num_samples
      gradients = self.X_data.T.dot(loss_grd)
      self.theta -= self.learning_rate * gradients


      if (epoch % 50) == 0:
        print(f"Epoch: {epoch} - Loss: {loss}")

    return {
        'loss': sum(self.losses)/len(self.losses),
        'weight': self.theta
    }

In [142]:
def r2score(y_pred, y):
  rss = np.sum((y_pred - y) ** 2)
  tss = np.sum((y - np.mean(y)) ** 2)
  r2 = 1 - (rss / tss)
  return r2

In [144]:
y_pred = np.array([1, 2, 3, 4, 5])
y = np.array([1, 2, 3, 4, 5])
print(r2score(y_pred, y))

y_pred = np.array([1, 2, 3, 4, 5])
y = np.array([3, 5, 5, 2, 4])
print(r2score(y_pred, y))




1.0
-2.235294117647059


In [145]:
def create_polynomial_features(X, degree = 2):
  X_poly = X.copy()
  for i in range(2, degree + 1):
    X_poly = np.c_[X_poly, X ** i]
  return X_poly

X = np.array([[1], [2], [3]])

In [157]:
def create_polynomial_features(X, degree = 2):
  X_mem = []
  for X_sub in X.T:
    X_sub = X_sub.T
    X_new = X_sub
    for i in range(2, degree + 1):
      X_new = np.c_[X_new, np.power(X_sub, degree)]
    X_mem.extend(X_new.T)
  return np.array(X_mem).T

In [158]:
X = np.array([[1,2], [2,3], [3,4]])

print(create_polynomial_features(X))

[[ 1  1  2  4]
 [ 2  4  3  9]
 [ 3  9  4 16]]


In [167]:
import pandas as pd
from sklearn.model_selection import train_test_split


In [190]:
df = pd.read_csv('/content/SalesPrediction.csv')

In [191]:
df = pd.get_dummies(df)
df

TV      Radio  Social Media       Sales  Influencer_Macro  \
0     16.0   6.566231      2.907983   54.732757             False   
1     13.0   9.237765      2.409567   46.677897             False   
2     41.0  15.886446      2.913410  150.177829             False   
3     83.0  30.020028      6.922304  298.246340             False   
4     15.0   8.437408      1.405998   56.594181             False   
...    ...        ...           ...         ...               ...   
4567  26.0   4.472360      0.717090   94.685866             False   
4568  71.0  20.610685      6.545573  249.101915             False   
4569  44.0  19.800072      5.096192  163.631457             False   
4570  71.0  17.534640      1.940873  253.610411              True   
4571  42.0  15.966688      5.046548  148.202414             False   

      Influencer_Mega  Influencer_Micro  Influencer_Nano  
0                True             False            False  
1                True             False            False  
2                True             False            False  
3                True             False            False  
4               False              True            False  
...               ...               ...              ...  
4567            False              True            False  
4568            False             False             True  
4569            False              True            False  
4570            False             False            False  
4571            False              True            False  

[4572 rows x 8 columns]

In [192]:
df = df.fillna(df.mean())

X = df [['TV' , 'Radio' , 'Social Media', 'Influencer_Macro' , 'Influencer_Mega' , 'Influencer_Micro' , 'Influencer_Nano']]
y = df['Sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [193]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_processed = scaler.fit_transform(X_train)
scaler.mean_[0]

54.173577723283785

In [194]:
X_test_processed = scaler.fit_transform(X_test)

In [195]:
from sklearn . preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures ( degree =2)
X_train_poly = poly_features.fit_transform (X_train_processed)
X_test_poly = poly_features.transform (X_test_processed)

In [198]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
poly_model = LinearRegression ()
poly_model .fit(X_train_poly , y_train)
preds = poly_model.predict (X_test_poly)
r2_score ( y_test , preds )

-2.2119776223197106e+21