In [5]:
import numpy as np

data=[['Sunny','Hot', 'High', 'Weak', 'no'],
      ['Sunny','Hot', 'High', 'Strong', 'no'],
      ['Overcast','Hot', 'High', 'Weak', 'yes'],
      ['Rain','Mild', 'High', 'Weak', 'yes'],
      ['Rain','Cool', 'Normal', 'Weak', 'yes'],
      ['Rain','Cool', 'Normal', 'Strong', 'no'],
      ['Overcast','Cool', 'Normal', 'Strong', 'yes'],
      ['Overcast','Mild', 'High', 'Weak', 'no'],
      ['Sunny','Cool', 'Normal', 'Weak', 'yes'],
      ['Rain','Mild', 'Normal', 'Weak', 'yes']
    ]

data = np.array(data)
print(data)

[['Sunny' 'Hot' 'High' 'Weak' 'no']
 ['Sunny' 'Hot' 'High' 'Strong' 'no']
 ['Overcast' 'Hot' 'High' 'Weak' 'yes']
 ['Rain' 'Mild' 'High' 'Weak' 'yes']
 ['Rain' 'Cool' 'Normal' 'Weak' 'yes']
 ['Rain' 'Cool' 'Normal' 'Strong' 'no']
 ['Overcast' 'Cool' 'Normal' 'Strong' 'yes']
 ['Overcast' 'Mild' 'High' 'Weak' 'no']
 ['Sunny' 'Cool' 'Normal' 'Weak' 'yes']
 ['Rain' 'Mild' 'Normal' 'Weak' 'yes']]


In [26]:
data[:,0]

array(['Sunny', 'Sunny', 'Overcast', 'Rain', 'Rain', 'Rain', 'Overcast',
       'Overcast', 'Sunny', 'Rain'], dtype='<U8')

In [49]:
def compute_prior_prob(data,x):
    y_unique = [['no', 'yes', ''],['Weak', 'Strong', ''],['High', 'Normal', ''],['Hot', 'Mild', 'Cool'],['Sunny', 'Overcast', 'Rain']]
    prior_prob = np.zeros((len(y_unique), 3))
    for i,text in enumerate(y_unique):
        for j in range(len(text)):
            prior_prob[i][j] = np.sum(data[:,x] == text[j])/len(data)
        x -= 1
        print(text)
        print(prior_prob[i])

compute_prior_prob(data,4)



['no', 'yes', '']
[0.4 0.6 0. ]
['Weak', 'Strong', '']
[0.7 0.3 0. ]
['High', 'Normal', '']
[0.5 0.5 0. ]
['Hot', 'Mild', 'Cool']
[0.3 0.3 0.4]
['Sunny', 'Overcast', 'Rain']
[0.3 0.3 0.4]


In [46]:
def compute_conditional_prob(data):
    y = ['no', 'yes']
    conditional_prob = []
    x = []
    for i in range(0, data.shape[1]-1):
        x = np.unique(data[:,i])
        print(x)

        x_conditional_prob = np.zeros((len(y), len(x)))
        for j in range(len(y)):
            for k in range(len(x)):
                x_conditional_prob[j][k] = np.sum((data[:,i] == x[k]) & (data[:,-1] == y[j]))/np.sum(data[:,-1] == y[j])
        conditional_prob.append(x_conditional_prob)
        print(x_conditional_prob)

compute_conditional_prob(data)

['Overcast' 'Rain' 'Sunny']
[[0.25       0.25       0.5       ]
 [0.33333333 0.5        0.16666667]]
['Cool' 'Hot' 'Mild']
[[0.25       0.5        0.25      ]
 [0.5        0.16666667 0.33333333]]
['High' 'Normal']
[[0.75       0.25      ]
 [0.33333333 0.66666667]]
['Strong' 'Weak']
[[0.5        0.5       ]
 [0.16666667 0.83333333]]


In [57]:
data2 = [['Weekday', 'Spring', 'None', 'None', 'On Time'],
         ['Weekday', 'Winter', 'None', 'Slight', 'On Time'],
         ['Weekday', 'Winter', 'None', 'None', 'On Time'],
         ['Holiday', 'Winter', 'High', 'Slight', 'Late'],
         ['Saturday', 'Summer', 'Normal', 'None', 'On Time'],
         ['Weekday', 'Autumn', 'Normal', 'None', 'Very Late'],
         ['Holiday', 'Summer', 'High', 'Slight', 'On Time'],
         ['Sunday', 'Summer', 'Normal', 'None', 'On Time'],
         ['Weekday', 'Winter', 'High', 'Heavy', 'Very Late'],
         ['Weekday', 'Summer', 'None', 'Slight', 'On Time'],
         ['Saturday', 'Spring', 'High', 'Heavy', 'Cancelled'],
         ['Weekday', 'Summer', 'High', 'Slight', 'On Time'],
         ['Weekday', 'Winter', 'Normal', 'None', 'Late'],
         ['Weekday', 'Summer', 'High', 'None', 'On Time'],
         ['Weekday', 'Winter', 'Normal', 'Heavy', 'Very Late'],
         ['Saturday', 'Autumn', 'High', 'Slight', 'On Time'],
         ['Weekday', 'Autumn', 'None', 'Heavy', 'On Time'],
         ['Holiday', 'Spring', 'Normal', 'Slight', 'On Time'],
         ['Weekday', 'Spring', 'Normal', 'None', 'On Time'],
         ['Weekday', 'Spring', 'Normal', 'Heavy', 'On Time']
        ]

data = np.array(data2)
print(data)

[['Weekday' 'Spring' 'None' 'None' 'On Time']
 ['Weekday' 'Winter' 'None' 'Slight' 'On Time']
 ['Weekday' 'Winter' 'None' 'None' 'On Time']
 ['Holiday' 'Winter' 'High' 'Slight' 'Late']
 ['Saturday' 'Summer' 'Normal' 'None' 'On Time']
 ['Weekday' 'Autumn' 'Normal' 'None' 'Very Late']
 ['Holiday' 'Summer' 'High' 'Slight' 'On Time']
 ['Sunday' 'Summer' 'Normal' 'None' 'On Time']
 ['Weekday' 'Winter' 'High' 'Heavy' 'Very Late']
 ['Weekday' 'Summer' 'None' 'Slight' 'On Time']
 ['Saturday' 'Spring' 'High' 'Heavy' 'Cancelled']
 ['Weekday' 'Summer' 'High' 'Slight' 'On Time']
 ['Weekday' 'Winter' 'Normal' 'None' 'Late']
 ['Weekday' 'Summer' 'High' 'None' 'On Time']
 ['Weekday' 'Winter' 'Normal' 'Heavy' 'Very Late']
 ['Saturday' 'Autumn' 'High' 'Slight' 'On Time']
 ['Weekday' 'Autumn' 'None' 'Heavy' 'On Time']
 ['Holiday' 'Spring' 'Normal' 'Slight' 'On Time']
 ['Weekday' 'Spring' 'Normal' 'None' 'On Time']
 ['Weekday' 'Spring' 'Normal' 'Heavy' 'On Time']]


In [66]:
def compute_prior_prob2(data, x):
    unique = [['On Time', 'Late', 'Very Late', 'Cancelled', ''],['None', 'Slight', 'Heavy', '', ''],['None', 'Normal', 'High', '', ''], ['Spring', 'Winter', 'Summer', 'Autumn', '']
              , ['Weekday', 'Saturday', 'Sunday', 'Holiday', '']
              ]
    prior_prob = np.zeros((len(unique), 5))
    for i,text in enumerate(unique):
        for j in range(len(text)):
            prior_prob[i][j] = np.sum(data[:,x] == text[j])/len(data)
            if (prior_prob[i][j] == 0.0000):
                prior_prob[i][j] = -1
        x -= 1
        print(text)
        print(prior_prob[i])

compute_prior_prob2(data, 4)

['On Time', 'Late', 'Very Late', 'Cancelled', '']
[ 0.7   0.1   0.15  0.05 -1.  ]
['None', 'Slight', 'Heavy', '', '']
[ 0.4   0.35  0.25 -1.   -1.  ]
['None', 'Normal', 'High', '', '']
[ 0.25  0.4   0.35 -1.   -1.  ]
['Spring', 'Winter', 'Summer', 'Autumn', '']
[ 0.25  0.3   0.3   0.15 -1.  ]
['Weekday', 'Saturday', 'Sunday', 'Holiday', '']
[ 0.65  0.15  0.05  0.15 -1.  ]


In [67]:
def compute_conditional_prob2(data, x):
    y = ['On Time', 'Late', 'Very Late', 'Cancelled']
    conditional_prob = []
    for i in range(0, data.shape[1]-1):
        x = np.unique(data[:,i])
        print(x)

        x_conditional_prob = np.zeros((len(y), len(x)))
        for j in range(len(y)):
            for k in range(len(x)):
                x_conditional_prob[j][k] = np.sum((data[:,i] == x[k]) & (data[:,-1] == y[j]))/np.sum(data[:,-1] == y[j])
        conditional_prob.append(x_conditional_prob)
        print(x_conditional_prob)

compute_conditional_prob2(data, 4)

['Holiday' 'Saturday' 'Sunday' 'Weekday']
[[0.14285714 0.14285714 0.07142857 0.64285714]
 [0.5        0.         0.         0.5       ]
 [0.         0.         0.         1.        ]
 [0.         1.         0.         0.        ]]
['Autumn' 'Spring' 'Summer' 'Winter']
[[0.14285714 0.28571429 0.42857143 0.14285714]
 [0.         0.         0.         1.        ]
 [0.33333333 0.         0.         0.66666667]
 [0.         1.         0.         0.        ]]
['High' 'None' 'Normal']
[[0.28571429 0.35714286 0.35714286]
 [0.5        0.         0.5       ]
 [0.33333333 0.         0.66666667]
 [1.         0.         0.        ]]
['Heavy' 'None' 'Slight']
[[0.14285714 0.42857143 0.42857143]
 [0.         0.5        0.5       ]
 [0.66666667 0.33333333 0.        ]
 [1.         0.         0.        ]]


In [68]:
iris_data = [[1.4, 0], [1.0 , 0],
             [1.3, 0], [0.9, 0],
             [2.0, 0], [1.8, 0],
             [3.0, 1], [3.8, 1],
             [4.1, 1], [3.9, 1],
             [4.2, 1], [3.4, 1]
]

iris_data = np.array(iris_data)
print(iris_data)

[[1.4 0. ]
 [1.  0. ]
 [1.3 0. ]
 [0.9 0. ]
 [2.  0. ]
 [1.8 0. ]
 [3.  1. ]
 [3.8 1. ]
 [4.1 1. ]
 [3.9 1. ]
 [4.2 1. ]
 [3.4 1. ]]


In [97]:
def gaussian_function(x, mean, std):
    return (1/(std*np.sqrt(2*np.pi)))*np.exp(-((x-mean)**2)/(2*(std**2)))

In [98]:
def compute_prior_prob_iris(data):
    y_unique = [0, 1]
    prior_prob = np.zeros(2)
    for i in range(len(y_unique)):
        prior_prob[i] = np.sum(data[:,1] == y_unique[i])/len(data)
        print(prior_prob[i])

In [ ]:
def train_gaussian_naive_bayes(data):
    #prior_probability = 
    compute_prior_prob_iris(data)
    #conditional_probability = 
    compute_conditional_prob_iris(data)
    #return prior_probability, conditional_probability

train_gaussian_naive_bayes(iris_data)
